apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 10s

  - name: Autopilot DB
    type: postgres
    access: proxy
    uid: autopilot-db
    url: postgres:5432
    user: autopilot
    secureJsonData:
      password: autopilot
    jsonData:
      database: autopilot
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
